services:

    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

    mysql:
      image: mysql:latest
      ports:
      - 3306:3306
      volumes:
        - mysql_data_container:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: abc123

    page-service:
      depends_on:
       - mongo
      image: kevinsegers/project-ar-backend/tree/experimental/page-service
      ports:
        - 8052:8052
      links:
       - mongo
      environment:
        MONGODB_PORT: 27017
        MONGODB_HOST: mongo

    book-service:
      depends_on:
        - mysql
      image: kevinsegers/project-ar-backend/tree/experimental/book-service
      ports:
        - 8051:8051
      links:
        - mysql
      environment:
        MYSQL_DB_USERNAME: root
        MYSQL_DB_PASSWORD: abc123
        MYSQL_DB_HOST: mysql

    brank-edge-service:
      depends_on:
        - book-service
        - page-service
      image: kevinsegers/project-ar-backend/tree/experimental/brank-edge-service
      ports:
        - 8050:8050
      links:
        - book-service
        - page-service
      environment:
        PAGE_SERVICE_BASEURL: page-service:8052
        BOOK__SERVICE_BASEURL: book-service:8051

volumes:
  mongodb_data_container:
  mysql_data_container: